### ISSUE TITLE
Can't use as a dependecny

### ISSUE THREAD

**Issue by PhyDoesStuff** [Catbuttes/axios-ntlm#1]
There are issues with the package that prevents use as a dependency:

- .gitignore suppresses /lib directory, but package.json expects the code to exist in /lib
- package.json expects a ntlmClient.d.ts, but no such file exists in /src (specifically victim of missing /lib directory or should actually be ntlm.d.ts?)

**Comment by Catbuttes** [comment]
The npm publish process didn't ignore those files, so using NPM should have worked happily. I have removed the lib directory from the gitignore and published the files as there was no real reason for them to not be included in git. You should find that the issues you raised are sorted now.
