### ISSUE TITLE
Сlarification in the processing of header data in ntlmClient.js

### ISSUE THREAD

**Issue by viscosity-medium** [Catbuttes/axios-ntlm#12]
Hello Dear friend!
I found that in the ntlmClient file.js you compare the contents of the 'www-authenticate' header from the very beginning, writing the ^ sign in regular expressions. 

![axios-ntlm-0](https://user-images.githubusercontent.com/64640965/169313489-d5f2b7b9-0a12-4101-b366-f2f0997f981f.jpg)

However, as my experience (or rather fiddler) has shown, there are cases when 2 'www-authenticate' headers are returned from the server, which differ only in case.

![axios-ntlm-1](https://user-images.githubusercontent.com/64640965/169313288-0db3fea6-75d4-499e-801a-220db5ae0cf4.jpg)

 In the node, it can be seen that these 2 headers become one 

![axios-ntlm-2](https://user-images.githubusercontent.com/64640965/169313292-49be03a3-bfc3-4357-8b36-5717e251545c.jpg)

and thus our comparison will always produce a discrepancy and, as a consequence, the error "Invalid argument". Can you please edit your file so that the comparison with NTLM *data* is not made from the beginning of the line?

**Comment by unilynx** [comment]
I think https://github.com/Catbuttes/axios-ntlm/pull/20 will solve this
