### ISSUE TITLE
Add interceptor manually

### ISSUE THREAD

**Issue by xaviermonin** [Catbuttes/axios-ntlm#25]
Hello,
Would it be possible to export the behavior that handles NTLM authentication? I would like to be able to control the creation of the axios client and add the interceptor myself.

Thanks

**Comment by vision10** [comment]
The interceptor function could be made so you can replace it with your own interceptor, but then you would need to make the ntlm login yourself and the functions for the message creation are not exported.

This would make sense if you want to replace the the whole ntlm with ntlmV2
