### ISSUE TITLE
Axios-ntlm client never returns

### ISSUE THREAD

**Issue by Altacry** [Catbuttes/axios-ntlm#4]
Hi, I'm trying to develop a telegram bot that uses NTLM connection to a server.
Since it cannot know if the credentials given are correct, I'm using the client response status value to check for 200 or 401 HTTP response codes.
When I type correct credentials everything works fine and my function quits with status 200. However if I type wrong credentials it get stuck in the await client call and never returns. The whole function is wrapped in a try-catch so no error is given. No other HTTP response codes are given.
Any timeout given as config to the ntlm client is not working.
Any suggestion?

**Comment by Altacry** [comment]
Found a work-around using a custom client call:
```
async function myAxiosNtlm(client:any, options:any):Promise<any>{
    client.CancelToken = axios.CancelToken;
    client.isCancel = axios.isCancel;
    const abort = client.CancelToken.source()
    const id = setTimeout(
        () => abort.cancel("Timeout of 8000ms."),
    8000
    );
    let response = await client({ cancelToken: abort.token, ...options });
    clearTimeout(id)
    return response;
}
```
This function takes as parameters client, that you generate with `NtlmClient(yourCredentials)`, and options (`{url: , method: , headers: {...} }`). It will return the response of your request.
It uses AxiosStatic instead of AxiosInstance, and has a functioning timeout function.
This way you can add a connection timeout to avoid infinite waiting.

**Comment by Catbuttes** [comment]
This should be fixed by #6

**Comment by xaviermonin** [comment]
Hi, I have the same issue with the last version (throw err).

I found a solution that fix this problem: add `error.config.headers["X-retry"] = "false";` after the line `let t3Msg = ntlm.createType3Message(t2Msg, credentials.username, credentials.password, credentials.workstation!, credentials.domain);` to prevent retrying.

I have an other case where axios-ntlm never returns. If the response of the server is a temporary redirect (302 HTTP status), axios-ntlm authenticate successfully to the initial path but try and retry indefinitely to the same path (redirected url is not supported).
I found a workaround by setting maxRedirection = 0 in agent, but is it possible to completely support HTTP redirect in axios-ntlm ?

**Comment by martudev** [comment]
Hi, have the same issue as @xaviermonin but in my case it enters in this if
`if (error.headers['www-authenticate'].length < 50)`
and keeps retrying with not timeout or something like that, i try to put `error.config.headers["X-retry"] = "false";` but this dont works for me, its stills retrying.. any idea about this error? Thanks for all
