### ISSUE TITLE
Unauthorised error is thrown when using stream to pipe the response 

### ISSUE THREAD

**Issue by serhiiminin** [Catbuttes/axios-ntlm#8]
When I use `responseType: 'stream'` I get the unauthorized error (401). 
https://github.com/axios/axios#axios-api

```            
const client = NtlmClient(credentials);

const response = await client({
   url: 'https://example.com',
   method: 'post',
   responseType: 'stream',
   data: { name: "Jack" },
});

response.data.pipe(fs.createWriteStream('ada_lovelace.jpg'));
```

I use version `1.2.1`

**Comment by ma-zal** [comment]
I confirm, this issue exists.

**Comment by manodupont** [comment]
+1

**Comment by arontsang** [comment]
+1

Can confirm this issue exists.

Also. Here is the fix.

https://github.com/Catbuttes/axios-ntlm/pull/11

**Comment by arontsang** [comment]
@serhiiminin please can you check if v1.3.0 fixes your issue. 😃

**Comment by serhiiminin** [comment]
Hi, sorry for the late reply. I was away for some time. 
I can confirm that the issue is gone. Unfortunately, I faced another issue. Now I am getting error 400 Bad Request when making POST requests with the same setup
